### ISSUE TITLE
Seems like it only imports the schema definitions

### ISSUE THREAD

**Issue by tbowmo** [NicolasGoeddel/ha-sqlite2mariadb#2]
I'm adapting your code to do a native / haos migration, but after running the script I now end up with a database with empty tables.

Looking through the code I found [this](https://github.com/NicolasGoeddel/ha-sqlite2mariadb/blob/3c9e15d963cc56e7f93f8fb17bddd9175fef0b1b/migrate.sh#L114C21-L115C6) odd looking part. It seems that every db::execute just imports the schema file. Or am I missing some thing?

Also, your script ends up calling with some MYSQL_xx.. variables, even though the rest of the script uses DB_xx

**Comment by NicolasGoeddel** [comment]
Thank you for helping out with adding additional migration methods! Much appreciated.
I will take a look at the odd looking part soon. At first glance it looks strange indeed. I don't know what happened there exactly.

**Comment by tbowmo** [comment]
I ran a test with my changes on a rpi with haos, and it seems to have done the right thing, as I'm now using mariadb, and have all my history from before.

Haven't done any tests with the docker compose settings, as I don't use that

**Comment by NicolasGoeddel** [comment]
That's really nice. I hope this script can be used with all kinds of installation methods in the future.
Btw I started a review in #3 with a suggestions and a question.

**Comment by tbowmo** [comment]
Did you click "finish review"? (I can't see any comments in the pr)

**Comment by NicolasGoeddel** [comment]
> Did you click "finish review"? (I can't see any comments in the pr)

lol. First time I am doing this on Github. That button was not that obvious like it is in Gitlab which I use mostly.

Well, sorry for the delayed review I guess. :grimacing:
